# Generated by Django 5.0.4 on 2025-03-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='detections/')),
            ],
        ),
    ]
